export class ParticipantsTable {
	public static participants: any = [
		{
			id: 1234,
			firstName: 'Dave',
			lastName: 'Newman',
			preferredName: '',
			ndisnumber: "431234567",
			gender: 'male',
			dob: new Date(2000, 6, 12),
			cob: 'Australia',
			ethnicity: 'Neither',
			addressline1: '19 Ogilvie Road',
			addressline2: '',
			postcode: '6152',
			city: 'Applecross',
			state: 'WA',
			carer: 1,
			carerFirstName: 'John',
			carerLastName: 'Smith',
			carerEmail: 'john@email.com',
			carerContact: '+88 8781 4 11254',
			carerRelation: 'Parent',
			country: 'Australia',
			childcare: '',
			childcareNa: true,
			school: '',
			schoolYear: null,
			schoolHome: false,
			schoolNa: true,
			uni: '',
			phone: '00 61 2 9826 5432',
			uniNa: true,
			occupation: 'Boss',
			employer: 'Himself',
			occupationNa: false,
			languageSpoken: 'English',
			interpreter: 'No'
		},
		{
			id: 1235,
			firstName: 'Sohel',
			lastName: 'Rana',
			preferredName: '',
			gender: 'male',
			ndisnumber: "432345678",
			dob: new Date(2000, 5, 11),
			cob: 'Australia',
			ethnicity: 'Neither',
			addressline1: '19 Ogilvie Road',
			addressline2: '',
			postcode: '6152',
			city: 'Applecross',
			state: 'WA',
			country: 'Australia',
			childcare: '',
			childcareNa: true,
			school: '',
			carer: 1,
			carerFirstName: 'John',
			carerLastName: 'Smith',
			carerEmail: 'john@email.com',
			carerContact: '+88 8781 4 11254',
			carerRelation: 'Parent',
			schoolYear: null,
			schoolHome: false,
			schoolNa: true,
			uni: '',
			phone: '00 61 2 9876 5432',
			uniNa: true,
			occupation: 'Boss',
			employer: 'Himself',
			occupationNa: false,
			languageSpoken: 'English',
			interpreter: 'No'
		},
		{
			id: 1236,
			firstName: 'Gustavo',
			lastName: 'Sessa',
			preferredName: '',
			ndisnumber: "433456789",
			gender: 'male',
			dob: new Date(2000, 6, 12),
			cob: 'Australia',
			ethnicity: 'Neither',
			addressline1: '28 Goderich Street',
			addressline2: '',
			postcode: '6004',
			city: 'East Perth',
			state: 'WA',
			country: 'Australia',
			childcare: '',
			childcareNa: true,
			carer: 1,
			carerFirstName: 'John',
			carerLastName: 'Smith',
			carerEmail: 'john@email.com',
			carerContact: '+88 8781 4 11254',
			carerRelation: 'Parent',
			school: '',
			schoolYear: null,
			schoolHome: false,
			schoolNa: true,
			uni: '',
			uniNa: true,
			phone: '00 61 2 9876 9832',
			occupation: 'Big Boss',
			employer: 'Himself',
			occupationNa: false,
			languageSpoken: 'English',
			interpreter: 'No'
		}
	];
}
